# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: numpy-base
  version: 1.23.5
source:
  patches:
    - patches/0001-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
  sha256: 1b1766d6f397c18153d40015ddfc79ddb715cabadc04d2d228d4e5a8bc4ded1a
  url: https://github.com/numpy/numpy/releases/download/v1.23.5/numpy-1.23.5.tar.gz
build:
  entry_points:
    - f2py = numpy.f2py.f2py2e:main
  number: 0
  string: py310h375b286_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - blas 1.0 openblas
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.10.11 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - cython 0.29.32 py310h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgfortran-ng 11.2.0 h00389a5_1
    - libgfortran5 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libopenblas 0.3.20 h043d6bf_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.3 h5eee18b_3
    - nomkl 3.0 0
    - openblas-devel 0.3.20 h06a4308_1
    - openssl 1.1.1s h7f8727e_0
    - pip 22.3.1 py310h06a4308_0
    - python 3.10.8 h7a1cb2a_1
    - readline 8.2 h5eee18b_0
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.40.0 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - blas * openblas
    - libgcc-ng >=11.2.0
    - libopenblas >=0.3.20,<1.0a0
    - libstdcxx-ng >=11.2.0
    - python >=3.10,<3.11.0a0
test:
  commands:
    - test -e $SP_DIR/numpy/distutils/site.cfg
about:
  description: 'NumPy is the fundamental package needed for scientific computing with
    Python.

    '
  dev_url: https://github.com/numpy/numpy
  doc_source_url: https://github.com/numpy/numpy/tree/main/doc
  doc_url: https://numpy.org/doc/stable/reference/
  home: https://numpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/numpy/numpy/blob/main/LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 13dc2f72-e655-4a52-baa9-619b7e2014b1
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
  remote_url: git@github.com:AnacondaRecipes/numpy-feedstock.git
  sha: 3d70a5ca694fb618e981339c3d06f1e9686f1c3d
