# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Nov 26 15:37:00 2023
# ------------------------------------------------

package:
  name: wheel
  version: 0.42.0
source:
  sha256: c45be39f7882c9d34243236f2d63cbd58039e360f85d0913425fbd7ceea617a8
  url: https://pypi.io/packages/source/w/wheel/wheel-0.42.0.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/wheel_1701013112704/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && /home/conda/feedstock_root/build_artifacts/wheel_1701013112704/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m installer --no-compile-bytecode wheel-*.whl
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_0
    - python 3.12.0 hab00c5b_0_cpython
    - python-installer 0.7.0 pyhd8ed1ab_0
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
    - wheel --help
  imports:
    - wheel
    - wheel.cli
  requires:
    - pip
about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231126.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/wheel-feedstock
  sha: 6055c5abe2e41cb175ecdc2444986a576414bc85
