# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Apr 10 12:06:28 2019
# ------------------------------------------------

package:
    name: nose-exclude
    version: 0.5.0
source:
    sha256: f78fa8b41eeb815f0486414f710f1eea0949e346cfb11d59ba6295ed69e84304
    url: https://pypi.io/packages/source/n/nose-exclude/nose-exclude-0.5.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/nose-exclude_1554898140388/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.0.3 py27_0
        - python 2.7.15 h721da81_1008
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.0 py27_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - wheel 0.33.1 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - nose
        - python
        - setuptools
test:
    imports:
        - nose_exclude
about:
    home: https://github.com/kgrandis/nose-exclude
    license: LGPL-2.1
    license_family: LGPL
    license_file: LICENSE
    summary: Exclude specific directories from nosetests runs.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - xhochy
