# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Nov 18 04:10:32 2023
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2023.11.17
source:
  sha256: 9b469f3a900bf28dc19b8cfbf8019bf47f7fdd1a65a1d4ffb98fc14166beb4d1
  url: https://pypi.io/packages/source/c/certifi/certifi-2023.11.17.tar.gz
build:
  number: '0'
  string: hbcca054_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231117.2.1
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/ca-certificates-feedstock
  sha: a2bdfcc95243fa89c18428af866786f5dd32aa45
