# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec 21 23:31:45 2023
# ------------------------------------------------

package:
  name: greenlet
  version: 3.0.3
source:
  sha256: 43374442353259554ce33599da8b692d5aa96f8976d567d4badf263371fbe491
  url: https://pypi.io/packages/source/g/greenlet/greenlet-3.0.3.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/greenlet_1703201576006/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install --no-deps --ignore-installed .
  string: py310hc6cd4ac_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_3
    - gxx_linux-64 12.3.0 h8a814eb_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_103
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.10.13 hd12c33a_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023c h71feb2d_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
test:
  imports:
    - greenlet
about:
  description: 'The greenlet package is a spin-off of Stackless, a version of CPython
    that

    supports micro-threads called "tasklets". Tasklets run pseudo-concurrently

    (typically in a single or a few OS-level threads) and are synchronized with

    data exchanges on "channels".


    A "greenlet", on the other hand, is a still more primitive notion of

    micro-thread with no implicit scheduling; coroutines, in other words. This

    is useful when you want to control exactly when your code runs. You can

    build custom scheduled micro-threads on top of greenlet; however, it seems

    that greenlets are useful on their own as a way to make advanced control

    flow structures. For example, we can recreate generators; the difference

    with Python''s own generators is that our generators can call nested

    functions and the nested functions can yield values too. Additionally,

    you don''t need a "yield" keyword. See the example in

    tests/test_generator.py.


    Greenlets are provided as a C extension module for the regular unmodified

    interpreter.


    Greenlets are lightweight coroutines for in-process concurrent programming.

    '
  dev_url: https://github.com/python-greenlet/greenlet
  doc_url: https://greenlet.readthedocs.io
  home: https://github.com/python-greenlet/greenlet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight in-process concurrent programming
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231221.2.1
  recipe-maintainers:
    - curtisalexander
    - nicoddemus
    - xhochy
  remote_url: https://github.com/conda-forge/greenlet-feedstock
  sha: fcddecea2408b80981614e972fdd28a293273f94
