CI: azure
_libgcc_mutex: 0.1 conda_forge
binutils_version: '2.40'
c_compiler: gcc
c_stdlib: sysroot
c_stdlib_version: '2.12'
cdt_name: cos6
channel_sources: conda-forge/label/sysroot-with-crypt,conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: linux-64
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
gcc_maj_ver: '13'
gcc_version: 13.2.0
ignore_build_only_deps:
- numpy
- python
libgfortran_soname: '5'
libgomp_ver: 1.0.0
lua: '5'
numpy: '1.22'
old_triplet: x86_64-conda_cos6-linux-gnu
openmp_ver: '4.5'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
r_base: '3.5'
sysroot_name: sysroot
sysroot_version: '2.12'
target_platform: linux-64
triplet: x86_64-conda-linux-gnu
use_system_gcc: 'False'
zip_keys:
- - sysroot_version
  - sysroot_name
  - triplet
  - old_triplet
  - cross_target_platform
- - c_stdlib_version
  - cdt_name
- - gcc_version
  - gcc_maj_ver
  - libgfortran_soname
