# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: libgfortran5
  version: 13.2.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
      - patches/libgomp-support-environ-null.patch
      - patches/new-allow-commands-in-main-specfile.patch
    sha256: 8cb4be3796651976f94b9356fa08d833524f62420d6292c5033a9a26af315078
    url: https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 6
  string: h43f5ff8_6
requirements:
  build:
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - gcc_bootstrap_linux-64 13.2.0 h498ce07_3
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h55db66e_0
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - sysroot_linux-64 2.12 he073ed8_16
  run:
    - libgcc-ng >=13.2.0
  run_constrained:
    - libgfortran-ng 13.2.0
test:
  commands:
    - test -f ${PREFIX}/lib/libgfortran.so
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU Fortran Runtime Library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240421.12.1
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
  remote_url: https://github.com/conda-forge/ctng-compilers-feedstock
  sha: c12920daa09b75d2fb6bdd4c4fc1a53f4449174b
