# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar 29 16:31:05 2023
# ------------------------------------------------

package:
  name: pandas
  version: 1.5.3
source:
  sha256: 74a3fd7e5a7ec052f183273dc7b0acd3a863edf7520f5d3a1765c04ffdb3b0b1
  url: https://github.com/pandas-dev/pandas/releases/download/v1.5.3/pandas-1.5.3.tar.gz
build:
  number: '1'
  script:
    - /home/conda/feedstock_root/build_artifacts/pandas_1680107563694/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
      --global-option="-j1" --no-use-pep517
  string: py310h9b08913_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_12
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_12
    - gxx_impl_linux-64 11.3.0 hab1b70f_19
    - gxx_linux-64 11.3.0 hc203a17_12
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-devel_linux-64 11.3.0 h210ce93_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - cython 0.29.33 py310heca2aa9_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libblas 3.9.0 16_linux64_openblas
    - libcblas 3.9.0 16_linux64_openblas
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgfortran-ng 12.2.0 h69a702a_19
    - libgfortran5 12.2.0 h337968e_19
    - libgomp 12.2.0 h65d4601_19
    - liblapack 3.9.0 16_linux64_openblas
    - libnsl 2.0.0 h7f98852_0
    - libopenblas 0.3.21 pthreads_h78a6416_3
    - libsqlite 3.40.0 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - numpy 1.21.6 py310h45f3432_0
    - openssl 3.1.0 h0b41bf4_0
    - pip 23.0.1 pyhd8ed1ab_0
    - python 3.10.10 he550d4f_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h8228510_1
    - setuptools 67.6.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - numpy >=1.21.6,<2.0a0
    - python >=3.10,<3.11.0a0
    - python-dateutil >=2.8.1
    - python_abi 3.10.* *_cp310
    - pytz >=2020.1
test:
  commands:
    - pip check
    - python -c "import pandas; pandas.test(extra_args=['-m not clipboard and not
      single_cpu', '--skip-slow', '--skip-network', '--skip-db', '-n=2'])"
  imports:
    - pandas
  requires:
    - boto3
    - hypothesis
    - numpy <1.24
    - pip
    - psutil
    - pytest >=6.0
    - pytest-asyncio >=0.17
    - pytest-cov
    - pytest-xdist >=1.31
    - tomli
about:
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/docs/
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Powerful data structures for data analysis, time series, and statistics
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - TomAugspurger
    - WillAyd
    - datapythonista
    - jorisvandenbossche
    - jreback
    - lithomas1
    - marcogorelli
    - mroeschke
    - msarahan
    - ocefpaf
    - phofl
    - simonjayhawkins
