# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 11 16:49:00 2020
# ------------------------------------------------

package:
    name: nose
    version: 1.3.7
source:
    sha256: f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
    url: https://pypi.io/packages/source/n/nose/nose-1.3.7.tar.gz
build:
    entry_points:
        - nosetests = nose:run_exit
    noarch: python
    number: '1006'
    script: /home/conda/feedstock_root/build_artifacts/nose_1602434998960/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: py_1006
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py39h079e4ff_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.9.0 h852b56e_3_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - tzdata 2020b h516909a_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3.6
test:
    commands:
        - pip check
        - nosetests --help
    imports:
        - nose
        - nose.ext
    requires:
        - pip
about:
    description: 'NOTE: Nose has been in maintenance mode for the past several years
        and will

        likely cease without a new person/team to take over maintainership. New

        projects should consider using Nose2, py.test, or just plain

        unittest/unittest2.

        '
    dev_url: https://github.com/nose-devs/nose/
    doc_url: https://nose.readthedocs.org
    home: http://readthedocs.org/docs/nose/
    license: LGPL-2.1-only
    license_file: lgpl.txt
    summary: Nose extends unittest to make testing easier
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mariusvniekerk
        - msarahan
        - ocefpaf
        - scopatz
