# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Feb 20 16:59:52 2024
# ------------------------------------------------

package:
  name: pooch
  version: 1.8.1
source:
  sha256: 27ef63097dd9a6e4f9d2694f5cfbf2f0a5defa44fccafec08d601e731d746270
  url: https://pypi.io/packages/source/p/pooch/pooch-1.8.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pooch_1708448481555/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.0 pyhd8ed1ab_1
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - setuptools_scm 8.0.4 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - packaging >=20.0
    - platformdirs >=2.5.0
    - python >=3.7
    - requests >=2.19.0
about:
  description: 'Pooch manages your remote data files. It automatically downloads and
    stores

    them in a local directory (using HTTP or FTP), with support for versioning,

    corruption checks, and custom download and post-processing operations.

    '
  dev_url: https://github.com/fatiando/pooch
  doc_url: https://www.fatiando.org/pooch
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A friend to fetch your data files
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240220.3.1
  recipe-maintainers:
    - dopplershift
    - leouieda
  remote_url: https://github.com/conda-forge/pooch-feedstock
  sha: 10d6d6fb74015e23af3a718fc3c4140c1aaabaae
