# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: openssl
  version: 3.3.0
source:
  sha256: 53e66b043322a606abf0087e7699a0e033a37fa13feb9742df35c3a33b18fb02
  url: http://www.openssl.org/source/openssl-3.3.0.tar.gz
build:
  no_link: lib/libcrypto.so.3.0
  number: 0
  run_exports:
    - openssl >=3.3.0,<4.0a0
  string: hd590300_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h1562d66_6
    - gcc_linux-64 12.3.0 h6477408_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h55db66e_0
    - libgcc-devel_linux-64 12.3.0 h2af2641_106
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgomp 13.2.0 hc881cc4_6
    - libsanitizer 12.3.0 h2af2641_6
    - libstdcxx-ng 13.2.0 h95c4c6d_6
    - libxcrypt 4.4.36 hd590300_1
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgomp 13.2.0 hc881cc4_6
  run:
    - ca-certificates
    - libgcc-ng >=12
  run_constrained:
    - pyopenssl >=22.1
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.3.0" openssl
  requires:
    - pkg-config
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: http://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20240430.1.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 167b1ad9b5af4862b23eb8eb0eb9580107d47b25
