# This file created by conda-build 3.27.0
# ------------------------------------------------

package:
  name: libopenblas
  version: 0.3.25
source:
  patches:
    - patches/0001-Fix-building-test_sbgemm.patch
  sha256: 4c25cb30c4bb23eddca05d7d0a85997b8db6144f5464ba7f8c09ce91e2f35543
  url: https://github.com/OpenMathLib/OpenBLAS/archive/v0.3.25.tar.gz
build:
  number: 0
  run_exports:
    - libopenblas >=0.3.25,<1.0a0
  string: pthreads_h413a1c8_0
  track_features: null
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - gfortran_impl_linux-64 12.3.0 hfcedea8_3
    - gfortran_linux-64 12.3.0 h7fe76b4_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgfortran5 13.2.0 ha4646dd_3
    - libgomp 13.2.0 h807b86a_3
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_3
    - libgfortran-ng 13.2.0 h69a702a_3
    - libgfortran5 13.2.0 ha4646dd_3
    - libgomp 13.2.0 h807b86a_3
  run:
    - libgcc-ng >=12
    - libgfortran-ng
    - libgfortran5 >=12.3.0
  run_constrained:
    - openblas >=0.3.25,<0.3.26.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libopenblasp-r0.3.25.so
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblasp-r0.3.25.so']"
  requires:
    - python *
about:
  dev_url: https://github.com/OpenMathLib/OpenBLAS
  home: http://www.openblas.net/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231120.2.1
  recipe-maintainers:
    - gillins
    - groutr
    - h-vetinari
    - isuruf
    - jakirkham
  remote_url: https://github.com/conda-forge/openblas-feedstock
  sha: 9970a52cfe65c15a43edbeb742a6c7c27a4060ce
